# Generated by Django 4.2.11 on 2024-05-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shortlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={},
        ),
        migrations.RemoveField(
            model_name='shortlink',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='shortlink',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shortlink',
            name='requests_count',
        ),
    ]
