# Generated by Django 4.2.11 on 2024-05-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_shortlink_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
