# Generated by Django 4.2.11 on 2024-05-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='full_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
